### ISSUE TITLE
14. I want to know the real size of the objects (e.g. 10x20 cm)

### ISSUE THREAD

**Issue by xoxkoo** [XRD10/photo-wall-planner#14]
### Description:
Show the real size of the photo object (it should be further discussed when and how the sizes will be displayed)
### Refinement:
If the issue needs a refinement -> Create new issues and link it as sub-issues in this issue

**Comment by simonfrayer** [comment]
An idea: The sizes should be displayed from when the objact has been placed (all the time or when selected), and I think a number below/next to the edge will do the job
