### ISSUE TITLE
2. Being ale to choose predefined ratio of a frame (both portrait and landscape)

### ISSUE THREAD

**Issue by simonfrayer** [XRD10/photo-wall-planner#2]
### Description:
There sould be a predefined frame model (prefab) in the app that the user can select and place it within the scene. The common ratios that we want are:

- 4 x 6 inches (10 x 15 cm)
- 5 x 7 inches (13 x 18 cm)
- 8 x 10 inches (20 x 25 cm)
- 12 x 12 inches (30 x 30 cm)
- 12 x 16 inches (30 x 40 cm)

**1 Unity unit = 1 meter (100cm)**

There should be both portrait and landscape for each ratio

Use those prefabs in the already existing object selector within the AR template:

![image](https://github.com/user-attachments/assets/3f2c5d96-0af2-43a5-8a84-5acbe2384a27)

### Refinement:
If the issue needs a refinement -> Create new issues and link it as sub-issues in this issue

**Comment by JcullenNZ** [comment]
Planned View1 - before scan
![20240925_Photowall_preview_1](https://github.com/user-attachments/assets/264feebf-4755-482e-bb4a-462e062c57a3)
Planned View2 - post scan
![20240925_Photowall_preview_2](https://github.com/user-attachments/assets/c91888b0-d04c-405f-af14-472b4d830d5b)
Possible View3 - choosing frames
![20240925_Photowall_preview_3](https://github.com/user-attachments/assets/a8ca5cab-3791-4d70-a210-2ba54285c6ff)
![20240925_Photowall_preview_4](https://github.com/user-attachments/assets/a74ac969-4c29-4e38-8f03-6e7f1dff61bc)
