### ISSUE TITLE
Move save button to an upper corner

### ISSUE THREAD

**Issue by simonfrayer** [XRD10/photo-wall-planner#29]
### Description:
Currently the **save** button is placed randomly on teh screen.

<img width="306" alt="image" src="https://github.com/user-attachments/assets/07b572d9-1060-4b97-bdc5-bb1d61d6ef63">

There should be the frames on the bottom and the save would be better of somewhere in an upper corner

### Refinement:
If the issue needs a refinement -> Create new issues and link it as sub-issues in this issue

**Comment by xoxkoo** [comment]
after discussion we decided to leave the button where it was before
