### ISSUE TITLE
Measurements are not showing on the images

### ISSUE THREAD

**Issue by JcullenNZ** [XRD10/photo-wall-planner#47]
### Description:
Measurements are too far behind the frame in the y direction so not showing.
### Refinement:
If the issue needs a refinement -> Create new issues and link it as sub-issues in this issue

**Comment by simonfrayer** [comment]
![Image](https://github.com/user-attachments/assets/297a6290-c814-4d63-b200-b8df8eddae46)

Fixed some positioning and other scale issues
